spring:
  application:
    name: AccessAnalyzer
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: 3000
server:
  tomcat:
    connection-timeout: 3s

ip-info:
  api: https://api.ipinfo.io/lite/
  token: ${IPINFO_TOKEN}